let test = document.querySelector("#test");
let test1 = document.querySelector("#test1");
let test2 = document.querySelector("#test2");
let test3 = document.querySelector("#test3");
const div1 = dom.create("<div>1</div>");
dom.before(test, div1);
const div2 = dom.create("<div>2</div>");
dom.after(test, div2);
const div3 = dom.create("<div>3</div>");
dom.append(test, div3);
const div4 = dom.create("<div>4</div>");
dom.wrap(test, div4);
dom.remove(test1);
dom.empty(test2);
dom.attr(test, "title", "hi");
console.log(dom.attr(test, "title"));
console.log(dom.text(test1));
dom.style(test, { border: "solid 1px red", color: "green" });
dom.siblings(test3);
